// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUf3LPe7mdoCkBMjSjGQOD7U9ZH1wC4jY',
    appId: '1:540924243156:web:c464f569be40e54af29f41',
    messagingSenderId: '540924243156',
    projectId: 'notesbyfarhan',
    authDomain: 'notesbyfarhan.firebaseapp.com',
    storageBucket: 'notesbyfarhan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyu49gHDMvlRBW5EBr2haf_BhOSEbTt4',
    appId: '1:540924243156:android:e6ab1536d147ef76f29f41',
    messagingSenderId: '540924243156',
    projectId: 'notesbyfarhan',
    storageBucket: 'notesbyfarhan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfnc0VFE_tT2slJxTxYKkYjRc2OP6bj0',
    appId: '1:540924243156:ios:46e776c5c5aab663f29f41',
    messagingSenderId: '540924243156',
    projectId: 'notesbyfarhan',
    storageBucket: 'notesbyfarhan.appspot.com',
    iosClientId: '540924243156-p2ber544ijeharns8379trl2pretbjqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDfnc0VFE_tT2slJxTxYKkYjRc2OP6bj0',
    appId: '1:540924243156:ios:46e776c5c5aab663f29f41',
    messagingSenderId: '540924243156',
    projectId: 'notesbyfarhan',
    storageBucket: 'notesbyfarhan.appspot.com',
    iosClientId: '540924243156-p2ber544ijeharns8379trl2pretbjqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
